const FETCH_INVOICES_ADD_START = "[invoices]/FETCH_INVOICES_ADD_START";
const FETCH_INVOICES_ADD_SUCCESS = "[invoices]/FETCH_INVOICES_ADD_SUCCESS";

const FETCH_INVOICES_GET_ALL_START = "[invoices]/FETCH_INVOICES_GET_ALL_START";
const FETCH_INVOICES_GET_ALL_SUCCESS = "[invoices]/FETCH_INVOICES_GET_ALL_SUCCESS";


export default {
    FETCH_INVOICES_ADD_START,
    FETCH_INVOICES_ADD_SUCCESS,
    FETCH_INVOICES_GET_ALL_START,
    FETCH_INVOICES_GET_ALL_SUCCESS,
}