const FETCH_CUSTOMERS_START = "[customers]/FETCH_CUSTOMERS_START";
const FETCH_CUSTOMERS_SUCCESS = "[customers]/FETCH_CUSTOMERS_SUCCESS";
const FETCH_CUSTOMER_DELETE_START = "[customers]/FETCH_CUSTOMER_DELETE_START";
const FETCH_CUSTOMER_DELETE_SUCCESS =
  "[customers]/FETCH_CUSTOMER_DELETE_SUCCESS";

export default {
  FETCH_CUSTOMERS_START,
  FETCH_CUSTOMERS_SUCCESS,
  FETCH_CUSTOMER_DELETE_START,
  FETCH_CUSTOMER_DELETE_SUCCESS
};
