const FETCH_CUSTOMERS_START = "[customers]/FETCH_CUSTOMERS_START";
const FETCH_CUSTOMERS_SUCCESS = "[customers]/FETCH_CUSTOMERS_SUCCESS";


export default { FETCH_CUSTOMERS_START, FETCH_CUSTOMERS_SUCCESS }