//customers get all types
const FETCH_CUSTOMERS_START = "[customers]/FETCH_CUSTOMERS_START";
const FETCH_CUSTOMERS_SUCCESS = "[customers]/FETCH_CUSTOMERS_SUCCESS";

//customer delete types
const FETCH_CUSTOMER_DELETE_START = "[customers]/FETCH_CUSTOMER_DELETE_START";
const FETCH_CUSTOMER_DELETE_SUCCESS =
  "[customers]/FETCH_CUSTOMER_DELETE_SUCCESS";

//customer add types
const FETCH_CUSTOMER_ADD_START = "[customers]/FETCH_CUSTOMER_ADD_START";
const FETCH_CUSTOMER_ADD_SUCCESS =
  "[customers]/FETCH_CUSTOMER_ADD_SUCCESS";

export default {
  FETCH_CUSTOMERS_START,
  FETCH_CUSTOMERS_SUCCESS,
  FETCH_CUSTOMER_DELETE_START,
  FETCH_CUSTOMER_DELETE_SUCCESS,
  FETCH_CUSTOMER_ADD_START,
  FETCH_CUSTOMER_ADD_SUCCESS
};
