const FETCH_PRODUCTS_ALL_GET_START = "[products]/FETCH_PRODUCTS_ALL_GET_START";
const FETCH_PRODUCTS_ALL_GET_SUCCESS = "[products]/FETCH_PRODUCTS_ALL_GET_SUCCESS";

export default {
    FETCH_PRODUCTS_ALL_GET_START,
    FETCH_PRODUCTS_ALL_GET_SUCCESS
}